---
title: "Welcome to my blog"
date: 2019-01-14
---
title: Ambivert coder's blog
author: Upasana Sinha
email: usinha62@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is going to cover some really useful stuff about learning and diving into the world of web development, especially for complete newbies. Such as helpful (and mostly free) resources, do's and dont's,etc. 

# social links
twitter_username: https://twitter.com/AmbivertCoder
github_username:  https://github.com/Usinha31

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
